-- BEAST MODE — Migração 016: expansão da biblioteca (26 exercícios novos, deduplicados
-- contra os 34 já existentes). Objetivo: nunca mais bater em "sem exercícios elegíveis"
-- e dar variedade real para lá de 2 meses de uso. (aplicada 2026-08-01)

insert into exercicios (id, nome, padrao, grupo_muscular, equipamento_necessario, nivel_min, contraindicado_se, descricao) values
('supino_inclinado_halteres', 'Supino inclinado com halteres', 'push', null, 'Halteres', 'intermedio', '{Ombro}',
  'Banco a 30°, descer os halteres até ao peitoral superior e empurrar mantendo os cotovelos a 45°.'),
('supino_declinado_barra', 'Supino declinado com barra', 'push', null, 'Barra e discos', 'avancado', '{Ombro}',
  'Deitado em banco declinado, descer a barra até à linha inferior do peito e empurrar com estabilidade.'),
('crossover_polia', 'Crossover na polia', 'isolamento', 'peito', 'Máquinas', 'intermedio', '{Ombro}',
  'Tronco ligeiramente inclinado à frente, cruzar as mãos à frente do corpo focando na contração do peitoral.'),
('arnold_press', 'Press Arnold', 'push', null, 'Halteres', 'avancado', '{Ombro}',
  'Iniciar com halteres à frente do peito (palmas viradas para ti), rodar os pulsos para fora enquanto empurras verticalmente.'),
('flexoes_declinadas', 'Flexões declinadas (pés elevados)', 'push', null, 'Mesa ou cadeira', 'intermedio', '{Ombro,Cervical}',
  'Pés num banco ou cadeira, mãos no chão. Descer o peito mantendo o corpo numa linha reta.'),
('flexoes_diamante', 'Flexões diamante', 'push', null, 'Sem equipamento', 'intermedio', '{Ombro}',
  'Juntar polegares e indicadores sob o peito. Flectir os cotovelos bem junto ao tronco.'),
('flexoes_arqueiro', 'Flexões arqueiro', 'push', null, 'Sem equipamento', 'avancado', '{Ombro}',
  'Flectir um braço enquanto estendes o outro lateralmente, alternando a carga por lado.'),
('remada_tbar', 'Remada T-bar', 'pull', null, 'Máquinas', 'intermedio', '{Lombar}',
  'Tronco inclinado a 45°, puxar a carga contra o peito/umbigo retraindo as escápulas.'),
('remada_unilateral_halter', 'Remada unilateral com halter', 'pull', null, 'Halteres', 'iniciante', '{Lombar}',
  'Apoiar joelho e mão no banco. Puxar o halter em direção à anca mantendo o cotovelo junto ao corpo.'),
('puxada_pega_invertida', 'Puxada com pega invertida (supinada)', 'pull', null, 'Máquinas', 'intermedio', '{Ombro}',
  'Palmas viradas para ti. Puxar a barra focando na amplitude total e participação do bícep.'),
('pullover_halter', 'Pullover com halter', 'isolamento', 'costas', 'Halteres', 'intermedio', '{Ombro}',
  'Deitado no banco, puxar a carga em arco com braços semi-estendidos desde acima da cabeça até à anca.'),
('rosca_barra_z', 'Rosca de bíceps com barra Z', 'isolamento', 'biceps', 'Barra e discos', 'iniciante', '{}',
  'Flectir os cotovelos mantendo-os fixos ao lado do tronco. Descer de forma controlada.'),
('rosca_martelo', 'Rosca martelo com halteres', 'isolamento', 'biceps', 'Halteres', 'iniciante', '{}',
  'Pegas neutras (palmas viradas para dentro). Elevar os halteres mantendo o pulso firme.'),
('rosca_inclinada', 'Rosca de bíceps em banco inclinado', 'isolamento', 'biceps', 'Halteres', 'intermedio', '{Ombro}',
  'Sentado num banco a 45°, flectir os braços aproveitando o maior estiramento do bícep.'),
('peso_morto_convencional', 'Peso morto convencional', 'hinge', null, 'Barra e discos', 'avancado', '{Lombar,Joelho}',
  'Barra junto às canelas, elevar a carga sincronizando a extensão de joelhos e anca.'),
('agachamento_sumo', 'Agachamento sumô', 'squat', null, 'Kettlebell', 'intermedio', '{Joelho,Anca}',
  'Pés afastados e pontas para fora. Agachar mantendo o tronco vertical e joelhos a acompanhar os pés.'),
('pistol_squat', 'Pistol squat (agachamento unilateral)', 'squat', null, 'Sem equipamento', 'avancado', '{Joelho,Anca}',
  'Agachar numa só perna com a outra estendida à frente. Requer força, mobilidade e equilíbrio.'),
('step_up', 'Step-up em cadeira/caixa', 'squat', null, 'Mesa ou cadeira', 'iniciante', '{Joelho}',
  'Subir o degrau empurrando pelo calcanhar da perna de cima sem dar impulso com a de baixo.'),
('nordic_curl', 'Nordic hamstring curl', 'isolamento', 'pernas', 'Sem equipamento', 'avancado', '{Joelho}',
  'De joelhos com pés presos/segurados, descer o tronco de forma controlada travando com os isquiotibiais.'),
('ponte_gluteos_unilateral', 'Ponte de glúteos unilateral', 'hinge', null, 'Sem equipamento', 'intermedio', '{Lombar}',
  'Deitado, elevar a anca apoiado apenas num calcanhar, contraindo o glúteo no topo.'),
('caminhada_monstro', 'Caminhada de monstro (mini-band)', 'isolamento', 'gluteos', 'Elásticos', 'iniciante', '{Anca}',
  'Elástico nos joelhos/tornozelos, dar passos laterais mantendo semi-flexão de joelhos.'),
('wall_sit', 'Agachamento isométrico na parede', 'isolamento', 'pernas', 'Sem equipamento', 'iniciante', '{Joelho}',
  'Costas na parede, joelhos a 90°. Manter a posição pelo tempo determinado.'),
('prancha_lateral_elevacao', 'Prancha lateral com elevação de anca', 'core', null, 'Sem equipamento', 'intermedio', '{Ombro,Lombar}',
  'Apoio lateral no antebraço, elevar e descer a anca criando uma linha reta da cabeça aos pés.'),
('vups', 'Abdominais V-up', 'core', null, 'Sem equipamento', 'intermedio', '{Lombar,Cervical}',
  'Deitado, elevar simultaneamente tronco e pernas estendidas até as mãos tocarem nos pés.'),
('ab_wheel', 'Roda abdominal (ab wheel)', 'core', null, 'Sem equipamento', 'avancado', '{Lombar,Ombro}',
  'De joelhos, deslizar a roda à frente mantendo a lombar neutra e puxar de volta pelo core.'),
('hanging_leg_raise', 'Elevação de pernas suspenso', 'core', null, 'Barra de porta', 'avancado', '{Lombar,Ombro}',
  'Suspenso na barra, elevar as pernas estendidas ou fletidas até à altura da anca/peito.'),
('pallof_press', 'Pallof press com elástico', 'core', null, 'Elásticos', 'intermedio', '{Lombar}',
  'Tensão lateral no elástico. Empurrar as mãos à frente sem deixar o tronco rodar.');
