-- BEAST MODE — Migração 032: biblioteca de 66 -> 130 exercícios (curados, cobrindo os
-- mesmos 6 padrões x 8 equipamentos, sem duplicar o que já existia). (aplicada 2026-08-11)

insert into exercicios (id, nome, padrao, grupo_muscular, equipamento_necessario, nivel_min, contraindicado_se, descricao) values
('flexoes_inclinadas_maos_elevadas','Flexões inclinadas (mãos elevadas)','push','peito','Sem equipamento','iniciante','{}','Mãos numa superfície elevada (banco/mesa), corpo em linha reta, descer o peito até perto da superfície, empurrar.'),
('flexoes_joelhos_apoiados','Flexões com joelhos apoiados','push','peito','Sem equipamento','iniciante','{}','Joelhos no chão, corpo alinhado da cabeça aos joelhos, descer o peito, empurrar controlado.'),
('flexoes_parede','Flexões na parede','push','peito','Sem equipamento','iniciante','{Ombro}','De pé, mãos na parede à largura dos ombros, aproximar o peito da parede e empurrar de volta.'),
('press_militar_barra','Press militar com barra','push','ombros','Barra e discos','avancado','{Ombro}','Barra à altura dos ombros, empurrar por cima da cabeça em linha reta, sem hiperestender a lombar.'),
('press_militar_halteres_sentado','Press militar sentado com halteres','push','ombros','Halteres','intermedio','{Ombro}','Sentado, halteres à altura dos ombros, empurrar por cima da cabeça, descer controlado.'),
('supino_reto_halteres','Supino reto com halteres','push','peito','Halteres','intermedio','{Ombro}','Deitado no banco, halteres sobre o peito, descer até cotovelos a 90°, empurrar sem bater os halteres.'),
('press_peito_maquina','Press de peito na máquina','push','peito','Máquinas','iniciante','{Ombro}','Sentado na máquina, pegas à altura do peito, empurrar em frente sem travar os cotovelos.'),
('press_peito_elastico','Press de peito com elástico','push','peito','Elásticos','iniciante','{}','Elástico preso atrás, empurrar os braços à frente na altura do peito, voltar controlado.'),
('press_militar_kettlebell','Press militar com kettlebell','push','ombros','Kettlebell','intermedio','{Ombro}','Kettlebell no rack position, empurrar por cima da cabeça, cotovelo alinhado, descer controlado.'),
('supino_unilateral_halter','Supino unilateral com halter','push','peito','Halteres','avancado','{Ombro}','Um halter de cada vez, core firme para não rodar o tronco, controlar a descida e a subida.'),
('flexoes_elastico','Flexões com elástico (resistência acrescida)','push','peito','Elásticos','intermedio','{Ombro}','Elástico à volta das costas e mãos, executar a flexão normal com resistência extra na subida.'),
('extensao_triceps_maquina','Extensão de tríceps na máquina','push','triceps','Máquinas','iniciante','{}','Sentado ou em pé na máquina, estender os cotovelos contra a resistência sem mover os ombros.'),
('press_pike','Press Pike (elevação pike para ombros)','push','ombros','Sem equipamento','intermedio','{Ombro,Cervical}','Posição de V invertido, dobrar os cotovelos e descer a cabeça em direção ao chão, empurrar de volta.'),
('extensao_triceps_halter_atras_cabeca','Extensão de tríceps atrás da cabeça com halter','push','triceps','Halteres','intermedio','{Ombro}','Halter atrás da cabeça com os dois braços, estender os cotovelos por cima, controlar a descida.'),
('remada_sentada_maquina','Remada sentada na máquina','pull','costas','Máquinas','iniciante','{}','Sentado, puxar as pegas em direção ao abdómen, omoplatas a juntarem-se, voltar controlado.'),
('puxada_pega_neutra','Puxada com pega neutra','pull','costas','Máquinas','iniciante','{Ombro}','Pegas paralelas, puxar a barra até ao peito, cotovelos junto ao corpo, voltar controlado.'),
('remada_baixa_polia','Remada baixa na polia','pull','costas','Máquinas','intermedio','{Lombar}','Sentado, pernas semi-flexionadas, puxar a pega até ao abdómen mantendo o tronco estável.'),
('chin_up','Elevações supinadas (chin-up)','pull','biceps','Barra de porta','avancado','{Ombro}','Pega supinada (palmas viradas para ti), puxar o corpo até o queixo passar a barra, descer controlado.'),
('remada_kettlebell','Remada com kettlebell','pull','costas','Kettlebell','intermedio','{}','Tronco inclinado à frente, puxar o kettlebell em direção à anca, cotovelo junto ao corpo.'),
('encolhimento_ombros_halteres','Encolhimento de ombros com halteres','pull','ombros','Halteres','iniciante','{Cervical}','Halteres ao lado do corpo, elevar os ombros em direção às orelhas, descer controlado.'),
('puxada_alta_elastico_porta','Puxada alta com elástico na barra de porta','pull','costas','Barra de porta','iniciante','{}','Elástico preso no topo da porta, puxar para baixo em direção ao peito, voltar controlado.'),
('remada_renegade','Remada renegade','pull','costas','Halteres','avancado','{Ombro,Lombar}','Posição de prancha com um halter em cada mão, remar alternadamente sem rodar as ancas.'),
('remada_pendlay','Remada Pendlay com barra','pull','costas','Barra e discos','avancado','{Lombar}','Tronco paralelo ao chão, barra parte do chão a cada repetição, puxar até ao abdómen.'),
('face_pull_maquina','Face pull na polia/máquina','pull','ombros','Máquinas','intermedio','{Ombro}','Corda à altura da cara, puxar separando as mãos, cotovelos altos, foco no deltoide posterior.'),
('agachamento_bulgaro','Agachamento búlgaro (afundo elevado)','squat','pernas','Mesa ou cadeira','avancado','{Joelho}','Pé de trás apoiado numa cadeira, descer o joelho da frente até quase tocar o chão.'),
('agachamento_maquina','Agachamento na máquina (guiada)','squat','pernas','Máquinas','intermedio','{Joelho}','Ombros sob os apoios, descer controlado até 90°, empurrar pelos calcanhares a subir.'),
('agachamento_elastico','Agachamento com elástico (resistência)','squat','pernas','Elásticos','iniciante','{Joelho}','Elástico sob os pés e nos ombros, ou à volta dos joelhos, agachar contra a resistência.'),
('agachamento_sumo_halteres','Agachamento sumô com halteres','squat','pernas','Halteres','intermedio','{Joelho,Anca}','Pés bem afastados, pontas viradas para fora, halter entre as pernas, descer mantendo o tronco ereto.'),
('box_squat','Agachamento até à caixa (box squat)','squat','pernas','Mesa ou cadeira','intermedio','{Joelho}','Agachar até tocar levemente numa caixa ou banco, sem sentar todo o peso, e subir.'),
('step_up_halteres','Step-up com halteres','squat','pernas','Halteres','intermedio','{Joelho}','Halteres nas mãos, subir para cima de um step/cadeira com uma perna, controlar a descida.'),
('afundo_reverso','Afundo reverso (peso do corpo)','squat','pernas','Sem equipamento','iniciante','{Joelho}','Passo para trás em vez de para a frente, descer até 90° no joelho da frente, voltar.'),
('afundo_caminhada','Afundo em caminhada (walking lunge)','squat','pernas','Sem equipamento','intermedio','{Joelho}','Afundos alternados avançando pelo espaço, tronco ereto, joelho da frente sobre o tornozelo.'),
('agachamento_kettlebell_duplo','Agachamento com dois kettlebells (front squat)','squat','pernas','Kettlebell','avancado','{Joelho,Ombro}','Kettlebells no rack position, cotovelos altos, agachar mantendo o tronco vertical.'),
('leg_press_unilateral','Leg press unilateral','squat','pernas','Máquinas','avancado','{Joelho}','Uma perna de cada vez na máquina, controlar a descida até 90°, empurrar sem travar o joelho.'),
('superman','Superman (extensão lombar)','hinge','gluteos','Sem equipamento','iniciante','{Lombar}','Deitado de barriga para baixo, elevar simultaneamente braços e pernas, segurar 1-2s, descer controlado.'),
('good_morning_elastico','Good morning com elástico','hinge','gluteos','Elásticos','intermedio','{Lombar}','Elástico sob os pés e nos ombros, dobrar a anca para a frente mantendo as costas retas.'),
('peso_morto_romeno_halteres','Peso morto romeno com halteres','hinge','gluteos','Halteres','intermedio','{Lombar}','Halteres à frente das coxas, dobrar a anca para trás mantendo pernas quase esticadas, costas retas.'),
('peso_morto_sumo_barra','Peso morto sumô com barra','hinge','gluteos','Barra e discos','avancado','{Lombar,Joelho}','Pés bem afastados, pega entre as pernas, subir a barra estendendo anca e joelhos ao mesmo tempo.'),
('hip_thrust_peso_corporal','Hip thrust sem carga (peso do corpo)','hinge','gluteos','Sem equipamento','iniciante','{}','Costas apoiadas num banco, pés no chão, elevar a anca contraindo os glúteos no topo.'),
('kickback_gluteo_elastico','Kickback de glúteo com elástico','hinge','gluteos','Elásticos','iniciante','{}','Elástico à volta dos tornozelos, de gatas, estender uma perna para trás contraindo o glúteo.'),
('peso_morto_unilateral_halter','Peso morto unilateral com halter','hinge','gluteos','Halteres','avancado','{Lombar}','Um halter numa mão, equilíbrio numa perna, dobrar a anca mantendo a perna de apoio quase esticada.'),
('cadeira_gluteos_maquina','Cadeira de glúteos na máquina','hinge','gluteos','Máquinas','intermedio','{}','Sentado ou apoiado na máquina, empurrar com o calcanhar contraindo o glúteo no fim do movimento.'),
('good_morning_barra','Good morning com barra','hinge','gluteos','Barra e discos','avancado','{Lombar}','Barra nos trapézios, dobrar a anca para a frente com joelhos quase esticados, costas neutras.'),
('ponte_gluteos_elastico','Ponte de glúteos com elástico','hinge','gluteos','Elásticos','iniciante','{}','Elástico acima dos joelhos, deitado, elevar a anca afastando ligeiramente os joelhos contra a resistência.'),
('abdominal_bicicleta','Abdominal bicicleta','core',NULL,'Sem equipamento','iniciante','{Cervical}','Deitado, pedalar no ar levando o cotovelo ao joelho oposto alternadamente, sem puxar o pescoço.'),
('prancha_elastico_antirotacao','Prancha com puxada de elástico (anti-rotação)','core',NULL,'Elásticos','intermedio','{Ombro}','Prancha lateral ou frontal, puxar o elástico sem deixar o tronco rodar.'),
('abdominal_maquina','Abdominal na máquina','core',NULL,'Máquinas','iniciante','{Lombar}','Sentado na máquina, flexionar o tronco contra a resistência, voltar controlado.'),
('dead_bug','Dead bug','core',NULL,'Sem equipamento','iniciante','{Lombar}','Deitado, braços e pernas ao ar, estender um braço e a perna oposta sem a lombar descolar do chão.'),
('hollow_hold','Hollow hold','core',NULL,'Sem equipamento','intermedio','{Lombar}','Deitado, elevar ombros e pernas do chão formando uma "banana", manter a posição sem arquear a lombar.'),
('rotacao_russa_halter','Rotação russa com halter','core',NULL,'Halteres','intermedio','{Lombar}','Sentado, tronco inclinado atrás, rodar o halter de um lado ao outro junto ao corpo.'),
('rotacao_russa_kettlebell','Rotação russa com kettlebell','core',NULL,'Kettlebell','intermedio','{Lombar}','Sentado, tronco inclinado atrás, rodar o kettlebell de um lado ao outro junto ao corpo.'),
('prancha_com_carga','Prancha com carga nas costas','core',NULL,'Barra e discos','avancado','{Lombar,Ombro}','Prancha normal com um disco colocado sobre a zona lombar/omoplatas, manter a posição.'),
('elevacao_pernas_cadeira','Elevação de pernas apoiado na cadeira','core',NULL,'Mesa ou cadeira','iniciante','{Lombar}','Sentado na borda de uma cadeira, mãos a segurar, elevar as pernas esticadas até à horizontal.'),
('abdominal_elastico_porta','Abdominal com elástico preso na porta','core',NULL,'Barra de porta','intermedio','{Cervical}','Elástico preso acima da cabeça na porta, ajoelhado, flexionar o tronco puxando o elástico para baixo.'),
('elevacao_panturrilha_maquina','Elevação de panturrilha na máquina','isolamento','pernas','Máquinas','iniciante','{}','Na máquina, subir na ponta dos pés o máximo possível, descer controlado até alongar a barriga da perna.'),
('elevacao_frontal_halteres','Elevação frontal com halteres','isolamento','ombros','Halteres','iniciante','{Ombro}','Halteres à frente das coxas, elevar os braços à frente até à altura dos ombros, descer controlado.'),
('rosca_biceps_maquina','Rosca de bíceps na máquina','isolamento','biceps','Máquinas','iniciante','{}','Sentado na máquina, flexionar os cotovelos contra a resistência sem mover os ombros.'),
('rosca_biceps_elastico','Rosca de bíceps com elástico','isolamento','biceps','Elásticos','iniciante','{}','Pés sobre o elástico, flexionar os cotovelos puxando as pegas até aos ombros.'),
('extensao_triceps_corda_polia','Extensão de tríceps na polia (corda)','isolamento','triceps','Máquinas','iniciante','{Ombro}','Corda na polia alta, cotovelos junto ao corpo, estender os braços separando as pontas da corda no fim.'),
('elevacao_lateral_kettlebell','Elevação lateral com kettlebell','isolamento','ombros','Kettlebell','intermedio','{Ombro}','Kettlebell numa mão, elevar o braço lateralmente até à altura do ombro, descer controlado.'),
('abducao_anca_elastico','Abdução de anca com elástico (glúteo médio)','isolamento','gluteos','Elásticos','iniciante','{Anca}','Elástico acima dos joelhos, de pé ou deitado de lado, afastar a perna lateralmente contra a resistência.'),
('panturrilha_step','Elevação de panturrilha num degrau/step','isolamento','pernas','Mesa ou cadeira','iniciante','{}','Ponta dos pés na borda de um degrau, descer o calcanhar abaixo do nível do step, subir na ponta.'),
('rosca_concentrada_halter','Rosca concentrada com halter','isolamento','biceps','Halteres','intermedio','{}','Sentado, cotovelo apoiado na coxa, flexionar o cotovelo isolando o bíceps, descer controlado.'),
('adutores_elastico','Adução de anca com elástico','isolamento','gluteos','Elásticos','iniciante','{Anca}','Elástico preso a um ponto fixo, puxar a perna para dentro do corpo contra a resistência.');
